name: Build and Deploy Build to Heroku on Tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install project dependencies with Yarn
        run: yarn install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'jaggaer-test'
          heroku_email: 'bojan.radicevic.83@gmail.com'
